const express = require('express');
const router = express.Router();
const usersController = require('../controller/users_controllers');
console.log(usersController);
router.get('/profile', usersController.profile);
router.get('/feed', usersController.feed);
router.get('/sign-in', usersController.signIn);
router.get('/sign-up', usersController.signUp);
router.post('/create', usersController.create);
router.post('/create-session', usersController.createSession);
router.post('/sign-in',usersController.signOut);
module.exports= router;